name: Goalify
description: "A social habit tracker where friends create groups, set a deadline, complete tasks for points, and compete on a live scoreboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  flutter_riverpod: ^2.5.1
  confetti: ^0.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase Core
  firebase_core: ^3.15.2

  # Authentication
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1

  # Firestore database
  cloud_firestore: ^5.6.12

  google_fonts: ^6.1.0

  # Push notifications
  firebase_messaging: ^15.1.2
  syncfusion_flutter_charts: ^30.2.4
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  fl_chart: 0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: assets/images/app_icon.png
    adaptive_icon_background: "#d42b28"


flutter:
  assets:
    - assets/images/placeholder.jpg
    - assets/images/default_group.jpg
    - assets/workouts.json
    - assets/images/exercises/
  uses-material-design: true



Error detected in pubspec.yaml:
No file or variants found for asset: assets/images/default_group.jpg.