name: goalify
description: "A social habit tracker where friends create groups, set a deadline, complete tasks for points, and compete on a live scoreboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management
  flutter_riverpod: ^2.5.1

  # Firebase Core
  firebase_core: ^3.5.0

  # Authentication
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1

  # Firestore database
  cloud_firestore: ^5.4.4

  google_fonts: ^6.1.0

  # Push notifications
  firebase_messaging: ^15.1.2
  syncfusion_flutter_charts: ^30.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/placeholder.jpg
    - assets/images/default_group.jpg
  uses-material-design: true

Error detected in pubspec.yaml:
No file or variants found for asset: assets/images/default_group.jpg.